"""Add stl_model to STLFile

Revision ID: 09f605ece946
Revises: 4720ecd943e1
Create Date: 2024-05-22 11:29:58.968693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f605ece946'
down_revision = '4720ecd943e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stl_model', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl_file', schema=None) as batch_op:
        batch_op.drop_column('stl_model')

    # ### end Alembic commands ###
