"""Add upload_date to STLFile

Revision ID: 4720ecd943e1
Revises: 77bc77443ec9
Create Date: 2024-05-22 08:35:28.517619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '4720ecd943e1'
down_revision = '77bc77443ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stl_file', sa.Column('upload_date', sa.DateTime(), nullable=True))
    
    # Set the current datetime for existing rows
    stl_file = table('stl_file', column('upload_date', sa.DateTime()))
    op.execute(stl_file.update().values({'upload_date': datetime.utcnow()}))

    # Make the column non-nullable
    with op.batch_alter_table('stl_file', schema=None) as batch_op:
        batch_op.alter_column('upload_date', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl_file', schema=None) as batch_op:
        batch_op.alter_column('upload_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
